services:
  stats-server:
    build:
      context: ./ewm-stats-service/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm_stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - stats-db-data:/var/lib/postgresql/data

  ewm-service:
    image: alpine
    container_name: ewm-service
    command: ["sleep", "infinity"]
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm_main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ewm-db-data:/var/lib/postgresql/data

volumes:
  stats-db-data:
  ewm-db-data:
